-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.message_logs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  channel text NOT NULL CHECK (channel IN ('sms', 'push')),
  recipient_user_id uuid REFERENCES public.users(id),
  recipient_phone text,
  title text,
  message text NOT NULL,
  status text NOT NULL CHECK (status IN ('sent', 'failed')),
  sent_by_user_id uuid REFERENCES public.users(id),
  external_id text,
  notification_type text,
  audience text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now()
);
CREATE INDEX idx_message_logs_created_at ON public.message_logs(created_at DESC);
CREATE INDEX idx_message_logs_channel ON public.message_logs(channel);

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])),
  old_data jsonb,
  new_data jsonb,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  actor_id uuid,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.driver_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  verification_status USER-DEFINED DEFAULT 'pending'::verification_status,
  verified_at timestamp with time zone,
  subscription_status USER-DEFINED DEFAULT 'expired'::subscription_status,
  subscription_start_date timestamp with time zone,
  subscription_end_date timestamp with time zone,
  monthly_fee_amount numeric DEFAULT 0,
  national_id_url text,
  drivers_license_url text,
  drivers_license_number character varying,
  drivers_license_expiry date,
  is_online boolean DEFAULT false,
  is_available boolean DEFAULT false,
  current_location USER-DEFINED,
  location_updated_at timestamp with time zone,
  total_trips integer DEFAULT 0,
  rating_average numeric DEFAULT 5.0,
  rating_count integer DEFAULT 0,
  acceptance_rate numeric DEFAULT 100.0,
  mmg_account_number character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT driver_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.location_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid,
  driver_id uuid,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  location USER-DEFINED,
  accuracy_meters numeric,
  speed_kmh numeric,
  heading numeric,
  recorded_at timestamp with time zone DEFAULT now(),
  device_id text,
  is_online boolean DEFAULT true,
  CONSTRAINT location_history_pkey PRIMARY KEY (id),
  CONSTRAINT location_history_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT location_history_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.driver_profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  title character varying NOT NULL,
  body text NOT NULL,
  notification_type character varying NOT NULL,
  related_entity_type character varying,
  related_entity_id uuid,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  push_sent boolean DEFAULT false,
  push_sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payment_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  subscription_id uuid,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'GYD'::character varying,
  payment_method character varying NOT NULL,
  mmg_transaction_id character varying,
  mmg_reference character varying,
  mmg_phone_number character varying,
  status USER-DEFINED NOT NULL,
  gateway_response jsonb,
  error_message text,
  initiated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT payment_transactions_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.rider_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  subscription_status USER-DEFINED DEFAULT 'trial'::subscription_status,
  subscription_start_date timestamp with time zone,
  subscription_end_date timestamp with time zone,
  trial_end_date timestamp with time zone,
  total_trips integer DEFAULT 0,
  rating_average numeric DEFAULT 5.0,
  rating_count integer DEFAULT 0,
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rider_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT rider_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.saved_places (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name character varying NOT NULL,
  address text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  location USER-DEFINED,
  place_type character varying DEFAULT 'other'::character varying CHECK (place_type::text = ANY (ARRAY['home'::character varying, 'work'::character varying, 'other'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT saved_places_pkey PRIMARY KEY (id),
  CONSTRAINT saved_places_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  user_role USER-DEFINED NOT NULL,
  plan_type character varying NOT NULL,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'GYD'::character varying,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  status USER-DEFINED NOT NULL,
  payment_method character varying,
  payment_reference character varying,
  payment_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.system_config (
  key character varying NOT NULL,
  value jsonb NOT NULL,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT system_config_pkey PRIMARY KEY (key),
  CONSTRAINT system_config_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.trip_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  rider_id uuid,
  pickup_latitude numeric NOT NULL,
  pickup_longitude numeric NOT NULL,
  pickup_address text NOT NULL,
  pickup_location USER-DEFINED,
  destination_latitude numeric,
  destination_longitude numeric,
  destination_address text,
  destination_location USER-DEFINED,
  trip_type USER-DEFINED NOT NULL,
  estimated_distance_km numeric,
  estimated_duration_minutes integer,
  estimated_fare numeric,
  notes text,
  passenger_count integer DEFAULT 1,
  status USER-DEFINED DEFAULT 'requested'::trip_status,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trip_requests_pkey PRIMARY KEY (id),
  CONSTRAINT trip_requests_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.rider_profiles(id)
);
CREATE TABLE public.trips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  rider_id uuid,
  driver_id uuid,
  vehicle_id uuid,
  request_id uuid,
  pickup_latitude numeric NOT NULL,
  pickup_longitude numeric NOT NULL,
  pickup_address text NOT NULL,
  destination_latitude numeric,
  destination_longitude numeric,
  destination_address text,
  trip_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL,
  estimated_distance_km numeric,
  actual_distance_km numeric,
  estimated_duration_minutes integer,
  actual_duration_minutes integer,
  estimated_fare numeric,
  actual_fare numeric,
  currency character varying DEFAULT 'GYD'::character varying,
  payment_method character varying DEFAULT 'cash'::character varying,
  route_polyline text,
  route_waypoints jsonb,
  requested_at timestamp with time zone NOT NULL,
  accepted_at timestamp with time zone,
  driver_arrived_at timestamp with time zone,
  picked_up_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  is_night_trip boolean DEFAULT false,
  rider_rating integer CHECK (rider_rating >= 1 AND rider_rating <= 5),
  driver_rating integer CHECK (driver_rating >= 1 AND driver_rating <= 5),
  rider_feedback text,
  driver_feedback text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cancelled_by_user_id uuid,
  completed_latitude numeric,
  completed_longitude numeric,
  driver_rating_friendly integer CHECK (driver_rating_friendly IS NULL OR driver_rating_friendly >= 1 AND driver_rating_friendly <= 5),
  driver_rating_clean integer CHECK (driver_rating_clean IS NULL OR driver_rating_clean >= 1 AND driver_rating_clean <= 5),
  driver_rating_safe integer CHECK (driver_rating_safe IS NULL OR driver_rating_safe >= 1 AND driver_rating_safe <= 5),
  driver_rating_communicated_fairly integer CHECK (driver_rating_communicated_fairly IS NULL OR driver_rating_communicated_fairly >= 1 AND driver_rating_communicated_fairly <= 5),
  CONSTRAINT trips_pkey PRIMARY KEY (id),
  CONSTRAINT trips_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.rider_profiles(id),
  CONSTRAINT trips_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.driver_profiles(id),
  CONSTRAINT trips_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT trips_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.trip_requests(id),
  CONSTRAINT trips_cancelled_by_user_id_fkey FOREIGN KEY (cancelled_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  auth_id uuid UNIQUE,
  phone_number character varying NOT NULL,
  email character varying UNIQUE,
  full_name character varying NOT NULL,
  profile_photo_url text,
  role USER-DEFINED NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_seen_at timestamp with time zone,
  preferred_language character varying DEFAULT 'en'::character varying,
  notification_enabled boolean DEFAULT true,
  fcm_token text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vehicles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  driver_id uuid,
  make character varying NOT NULL,
  model character varying NOT NULL,
  year integer,
  color character varying,
  license_plate character varying NOT NULL UNIQUE,
  vehicle_photo_url text,
  registration_url text,
  registration_number character varying,
  registration_expiry date,
  insurance_expiry date,
  is_active boolean DEFAULT true,
  is_primary boolean DEFAULT false,
  passenger_capacity integer DEFAULT 4,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT vehicles_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.driver_profiles(id)
);
CREATE TABLE public.verification_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  driver_id uuid,
  admin_id uuid,
  previous_status USER-DEFINED,
  new_status USER-DEFINED NOT NULL,
  admin_notes text,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT verification_logs_pkey PRIMARY KEY (id),
  CONSTRAINT verification_logs_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.driver_profiles(id),
  CONSTRAINT verification_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.users(id)
);